"""create videoclip table

Revision ID: 4228108e3a5c
Revises: 56ddce850fd3
Create Date: 2022-09-10 18:52:50.887929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4228108e3a5c'
down_revision = '56ddce850fd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videoclip',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.Column('uploaded', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_id', sa.String(length=64), nullable=False),
    sa.Column('author_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk__videoclip__author_id__user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__videoclip'))
    )
    op.create_index(op.f('ix__videoclip__hash_id'), 'videoclip', ['hash_id'], unique=True)
    op.create_index(op.f('ix__videoclip__name'), 'videoclip', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__videoclip__name'), table_name='videoclip')
    op.drop_index(op.f('ix__videoclip__hash_id'), table_name='videoclip')
    op.drop_table('videoclip')
    # ### end Alembic commands ###
