"""create review table

Revision ID: 845967842468
Revises: 4228108e3a5c
Create Date: 2022-09-11 20:45:38.351308

"""
from alembic import op
import sqlalchemy as sa

from fastapi_users_db_sqlalchemy.generics import GUID


# revision identifiers, used by Alembic.
revision = '845967842468'
down_revision = '4228108e3a5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('imagepath', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('hash_id', sa.String(length=64), nullable=False),
    sa.Column('published', sa.DateTime(timezone=True), nullable=True),
    sa.Column('videoclip_id', GUID(), nullable=True),
    sa.Column('author_id', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk__review__author_id__user')),
    sa.ForeignKeyConstraint(['videoclip_id'], ['videoclip.id'], name=op.f('fk__review__videoclip_id__videoclip')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__review'))
    )
    op.create_index(op.f('ix__review__hash_id'), 'review', ['hash_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__review__hash_id'), table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
